name: Release

on:
  push:
    branches:
      - main
jobs:
  cd:
    name: Continuous Delivery
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install package
        run: |
          pip install -e .
      - name: Set Version
        id: version
        run: |
          echo "::set-output name=PKG_VERSION::$(pip show filedgr_lib_ipfs | grep Version | sed 's/Version://g' | sed 's/ //g')"
      - name: Get Short Sha
        id: sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.PKG_VERSION }}
          draft: false
          prerelease: false